spring:
  profiles:
    active: dev
    include: oauth, redis, file

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  thymeleaf:
    enabled: false

---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: prod